post react
apbodrov/esphome-yaml-constructor pull request #12
Opened 2023-02-22 16:05 UTC by Kalibri1995

2023-02-26 17:38 UTC, apbodrov commented on lib/methods.py
> +    # with open(f'{UPLOADED_FILES_PATH}{file_name}.yaml', "wb") as uploaded_file:
закомментированный код смело выпилвай

2023-04-06 21:00 UTC, apbodrov requested changes

2023-04-06 21:00 UTC, apbodrov commented on main.py
> +    "http://localhost:3000",
соседний мерж реквест можно к себе подмержить

2023-04-08 16:26 UTC, apbodrov approved these changes

2023-04-15 16:30 UTC, denlo-0 approved these changes

2023-04-15 16:41 UTC, merged